### ISSUE TITLE
Lovelace tab not rendering if title is empty

### ISSUE THREAD

**Issue by TASSDevon** [MCrissDev/Ariela#172] opened 2019-12-11 19:22 UTC
If a tab has an empty title (but e.g. does have an mdi icon), it is rendered in the webUI but not in Ariela.

**Comment by MCrissDev** [comment] 2020-02-05 10:19
Hi,
I tested on latest version and i cannot reproduce.
Can you tell me if the latest version still has this issue?

**Comment by MCrissDev** [comment] 2021-01-02 11:36
Closing as cannot reproduce

**Closed by MCrissDev** 2021-01-02 11:36 UTC
